[workspace]
members = [
    "lib",
    "program",
    "server",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "0.7.7"
hex = "0.4.3"
sp1-sdk = "3.0.0"
clap = { version = "4.0", features = ["derive", "env"] }
tokio = "1.41.1"
web3 = "0.19"
